INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(493,1,1,'The Best Of Men At Work',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(494,1,4,'For Those About To Rock We Salute You',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(495,1,4,'Let There Be Rock',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(496,1,5,'Balls to the Wall',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(497,1,5,'Restless and Wild',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(498,1,7,'Big Ones',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(499,1,9,'Jagged Little Pill',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(500,1,10,'Facelift',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(501,1,15,'Audioslave',10,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(502,1,37,'Chronicle, Vol. 1',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(503,1,37,'Chronicle, Vol. 2',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(504,1,38,'Into The Light',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(505,1,39,'Come Taste The Band',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(506,1,39,'Deep Purple In Rock',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(507,1,39,'Fireball',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(508,1,39,'Machine Head',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(509,1,39,'MK III The Final Concerts [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(510,1,39,'Purpendicular',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(511,1,39,'Slaves And Masters',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(512,1,39,'Stormbringer',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(513,1,39,'The Battle Rages On',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(514,1,39,'The Final Concerts (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(515,1,43,'Un-Led-Ed',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(516,1,50,'King For A Day Fool For A Lifetime',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(517,1,52,'In Your Honor [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(518,1,52,'In Your Honor [Disc 2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(519,1,52,'The Colour And The Shape',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(520,1,53,'Bongo Fury',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(521,1,59,'Appetite for Destruction',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(522,1,59,'Use Your Illusion I',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(523,1,61,'A Matter of Life and Death',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(524,1,61,'Brave New World',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(525,1,61,'Fear Of The Dark',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(526,1,61,'Live At Donington 1992 (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(527,1,61,'Live At Donington 1992 (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(528,1,61,'Rock In Rio [CD2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(529,1,61,'The Number of The Beast',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(530,1,61,'The X Factor',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(531,1,61,'Virtual XI',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(532,1,63,'Emergency On Planet Earth',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(533,1,64,'Are You Experienced?',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(534,1,65,'Surfing with the Alien (Remastered)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(535,1,70,'Greatest Kiss',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(536,1,70,'Unplugged [Live]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(537,1,71,'BBC Sessions [Disc 1] [Live]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(538,1,71,'BBC Sessions [Disc 2] [Live]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(539,1,71,'Coda',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(540,1,71,'Houses Of The Holy',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(541,1,71,'In Through The Out Door',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(542,1,71,'IV',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(543,1,71,'Led Zeppelin I',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(544,1,71,'Led Zeppelin II',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(545,1,71,'Led Zeppelin III',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(546,1,71,'Physical Graffiti [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(547,1,71,'Physical Graffiti [Disc 2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(548,1,71,'Presence',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(549,1,71,'The Song Remains The Same (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(550,1,71,'The Song Remains The Same (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(551,1,73,'Greatest Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(552,1,77,'Misplaced Childhood',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(553,1,88,'Nevermind',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(554,1,89,'Compositores',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(555,1,93,'Bark at the Moon (Remastered)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(556,1,93,'Blizzard of Ozz',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(557,1,93,'Diary of a Madman (Remastered)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(558,1,93,'No More Tears (Remastered)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(559,1,93,'Speak of the Devil',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(560,1,94,'Walking Into Clarksdale',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(561,1,95,'The Beast Live',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(562,1,96,'Live On Two Legs [Live]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(563,1,96,'Riot Act',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(564,1,96,'Ten',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(565,1,96,'Vs.',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(566,1,97,'Dark Side Of The Moon',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(567,1,98,'Greatest Hits I',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(568,1,98,'Greatest Hits II',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(569,1,98,'News Of The World',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(570,1,99,'New Adventures In Hi-Fi',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(571,1,100,'Raul Seixas',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(572,1,101,'By The Way',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(573,1,101,'Californication',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(574,1,104,'Retrospective I (1974-1980)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(575,1,105,'Santana - As Years Go By',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(576,1,105,'Santana Live',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(577,1,105,'Supernatural',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(578,1,109,'Maquinarama',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(579,1,109,'O Samba Pocone',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(580,1,110,'A-Sides',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(581,1,113,'Core',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(582,1,116,'[1997] Black Light Syndrome',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(583,1,119,'Beyond Good And Evil',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(584,1,120,'The Doors',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(585,1,122,'The Police Greatest Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(586,1,123,'Every Kind of Light',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(587,1,124,'Hot Rocks, 1964-1971 (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(588,1,124,'No Security',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(589,1,124,'Voodoo Lounge',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(590,1,125,'My Generation - The Very Best Of The Who',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(591,1,128,'Achtung Baby',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(592,1,128,'B-Sides 1980-1990',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(593,1,128,'How To Dismantle An Atomic Bomb',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(594,1,128,'Pop',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(595,1,128,'Rattle And Hum',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(596,1,128,'The Best Of 1980-1990',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(597,1,128,'War',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(598,1,128,'Zooropa',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(599,1,130,'Diver Down',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(600,1,130,'The Best Of Van Halen, Vol. I',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(601,1,130,'Van Halen III',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(602,1,130,'Van Halen',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(603,1,132,'Contraband',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(604,2,2,'A Copland Celebration, Vol. I',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(605,2,6,'Gorecki: Symphony No. 3',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(606,2,16,'The Last Night of the Proms',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(607,2,17,'Sibelius: Finlandia',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(608,2,18,'Mozart: Symphonies Nos. 40 & 41',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(609,2,22,'Carmina Burana',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(610,2,23,'A Soprano Inspired',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(611,2,30,'Scheherazade',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(612,2,34,'SCRIABIN: Vers la flamme',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(613,2,45,'Adams, John: The Chairman Dances',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(614,2,47,'Pachelbel: Canon & Gigue',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(615,2,49,'Respighi:Pines of Rome',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(616,2,49,'Strauss: Waltzes',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(617,2,58,'Nielsen: The Six Symphonies',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(618,2,62,'Mascagni: Cavalleria Rusticana',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(619,2,69,'Weill: The Seven Deadly Sins',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(620,2,74,'Tchaikovsky: The Nutcracker',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(621,2,79,'Szymanowski: Piano Works, Vol. 1',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(622,2,81,'Berlioz: Symphonie Fantastique',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(623,2,81,'Prokofiev: Romeo & Juliet',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(624,2,86,'Mozart: Chamber Music',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(625,2,87,'The Best of Beethoven',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(626,2,91,'Bach: The Brandenburg Concertos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(627,2,102,'Purcell: The Fairy Queen',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(628,2,103,'Haydn: Symphonies 99 - 104',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(629,2,106,'Handel: The Messiah (Highlights)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(630,2,107,'Prokofiev: Symphony No.1',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(631,2,108,'Wagner: Favourite Overtures',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(632,2,117,'South American Getaway',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(633,2,121,'English Renaissance',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(634,2,127,'Bach: Toccata & Fugue in D Minor',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(635,2,134,'Bach: Goldberg Variations',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(636,2,135,'Bartok: Violin & Viola Concertos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(637,2,136,'Bach: The Cello Suites',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(638,3,3,'Worlds',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(639,3,8,'Quiet Songs',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(640,3,13,'Warner 25 Anos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(641,3,19,'The Best Of Billy Cobham',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(642,3,40,'Outbreak',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(643,3,55,'Quanta Gente Veio ver--Bonus De Carnaval',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(644,3,60,'Blue Moods',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(645,3,82,'Miles Ahead',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(646,3,82,'The Essential Miles Davis [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(647,3,82,'The Essential Miles Davis [Disc 2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(648,3,111,'Heart of the Night',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(649,3,111,'Morning Dance',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(650,4,11,'Frank',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(651,4,131,'Axe Bahia 2001',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(652,5,12,'Ring My Bell',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(653,5,29,'Le Freak',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(654,5,42,'MacArthur Park Suite',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(655,6,13,'Chill: Brazil (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(656,6,25,'Prenda Minha',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(657,6,25,'Sozinho Remix Ao Vivo',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(658,6,28,'Cassia Eller - Sem Limite [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(659,6,31,'Minha Historia',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(660,6,32,'Afrociberdelia',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(661,6,32,'Da Lama Ao Caos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(662,6,36,'Na Pista',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(663,6,41,'Djavan Ao Vivo - Vol. 02',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(664,6,41,'Djavan Ao Vivo - Vol. 1',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(665,6,44,'The Best of Ed Motta',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(666,6,46,'Elis Regina-Minha Historia',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(667,6,48,'Unplugged',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(668,6,51,'Deixa Entrar',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(669,6,54,'Roda De Funk',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(670,6,55,'Quanta Gente Veio Ver (Live)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(671,6,57,'Meus Momentos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(672,6,66,'Jorge Ben Jor 25 Anos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(673,6,67,'Jota Quest-1995',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(674,6,72,'Mais Do Mesmo',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(675,6,75,'Duos II',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(676,6,76,'Chill: Brazil (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(677,6,78,'Barulhinho Bom',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(678,6,83,'Milton Nascimento Ao Vivo',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(679,6,83,'Minas',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(680,6,90,'Olodum',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(681,6,92,'Acustico MTV',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(682,6,92,'Arquivo II',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(683,6,92,'Arquivo Os Paralamas Do Sucesso',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(684,6,126,'Serie Sem Limite (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(685,6,126,'Serie Sem Limite (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(686,6,131,'Sambas De Enredo 2001',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(687,6,131,'Vozes do MPB',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(688,6,133,'Vinicius De Moraes',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(689,6,137,'Ao Vivo [IMPORT]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(690,7,14,'Plays Metallica By Four Cellos',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(691,7,20,'Alcohol Fueled Brewtality Live! [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(692,7,20,'Alcohol Fueled Brewtality Live! [Disc 2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(693,7,21,'Black Sabbath Vol. 4 (Remaster)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(694,7,21,'Black Sabbath',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(695,7,24,'Chemical Wedding',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(696,7,56,'Faceless',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(697,7,59,'Use Your Illusion II',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(698,7,61,'A Real Dead One',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(699,7,61,'A Real Live One',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(700,7,61,'Live After Death',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(701,7,61,'No Prayer For The Dying',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(702,7,61,'Piece Of Mind',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(703,7,61,'Powerslave',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(704,7,61,'Rock In Rio [CD1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(705,7,61,'Rock In Rio [CD2]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(706,7,61,'Seventh Son of a Seventh Son',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(707,7,61,'Somewhere in Time',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(708,7,61,'The Number of The Beast',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(709,7,68,'Living After Midnight',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(710,7,73,'Greatest Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(711,7,80,'...And Justice For All',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(712,7,80,'Black Album',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(713,7,80,'Garage Inc. (Disc 1)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(714,7,80,'Garage Inc. (Disc 2)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(715,7,80,'Load',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(716,7,80,'Master Of Puppets',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(717,7,80,'ReLoad',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(718,7,80,'Ride The Lightning',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(719,7,80,'St. Anger',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(720,7,84,'Motley Crue Greatest Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(721,7,85,'Ace Of Spades',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(722,7,93,'Tribute',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(723,7,114,'Mezmerize',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(724,8,15,'Revelations',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(725,8,26,'Cake: B-Sides and Rarities',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(726,8,27,'Carried to Dust (Bonus Track Version)',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(727,8,33,'Carry On',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(728,8,115,'Temple of the Dog',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(729,9,35,'Acustico MTV [Live]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(730,9,35,'Cidade Negra - Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(731,9,73,'Greatest Hits',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(732,9,129,'UB40 The Best Of - Volume Two [UK]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(733,10,48,'The Cream Of Clapton',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(734,10,48,'Unplugged',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(735,10,61,'Iron Maiden',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(736,10,112,'In Step',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(737,10,118,'Live [Disc 1]',8.99,'Content/Images/placeholder.gif');
INSERT INTO Albums(AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl) VALUES(738,10,118,'Live [Disc 2]',8.99,'Content/Images/placeholder.gif');
