INSERT INTO Artists(ArtistId,Name) VALUES(1,'Men At Work');
INSERT INTO Artists(ArtistId,Name) VALUES(2,'Aaron Copland & London Symphony Orchestra');
INSERT INTO Artists(ArtistId,Name) VALUES(3,'Aaron Goldberg');
INSERT INTO Artists(ArtistId,Name) VALUES(4,'AC/DC');
INSERT INTO Artists(ArtistId,Name) VALUES(5,'Accept');
INSERT INTO Artists(ArtistId,Name) VALUES(6,'Adrian Leaper & Doreen de Feis');
INSERT INTO Artists(ArtistId,Name) VALUES(7,'Aerosmith');
INSERT INTO Artists(ArtistId,Name) VALUES(8,'Aisha Duo');
INSERT INTO Artists(ArtistId,Name) VALUES(9,'Alanis Morissette');
INSERT INTO Artists(ArtistId,Name) VALUES(10,'Alice In Chains');
INSERT INTO Artists(ArtistId,Name) VALUES(11,'Amy Winehouse');
INSERT INTO Artists(ArtistId,Name) VALUES(12,'Anita Ward');
INSERT INTO Artists(ArtistId,Name) VALUES(13,'Antonio Carlos Jobim');
INSERT INTO Artists(ArtistId,Name) VALUES(14,'Apocalyptica');
INSERT INTO Artists(ArtistId,Name) VALUES(15,'Audioslave');
INSERT INTO Artists(ArtistId,Name) VALUES(16,'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO Artists(ArtistId,Name) VALUES(17,'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO Artists(ArtistId,Name) VALUES(18,'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO Artists(ArtistId,Name) VALUES(19,'Billy Cobham');
INSERT INTO Artists(ArtistId,Name) VALUES(20,'Black Label Society');
INSERT INTO Artists(ArtistId,Name) VALUES(21,'Black Sabbath');
INSERT INTO Artists(ArtistId,Name) VALUES(22,'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO Artists(ArtistId,Name) VALUES(23,'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO Artists(ArtistId,Name) VALUES(24,'Bruce Dickinson');
INSERT INTO Artists(ArtistId,Name) VALUES(25,'Caetano Veloso');
INSERT INTO Artists(ArtistId,Name) VALUES(26,'Cake');
INSERT INTO Artists(ArtistId,Name) VALUES(27,'Calexico');
INSERT INTO Artists(ArtistId,Name) VALUES(28,'Cassia Eller');
INSERT INTO Artists(ArtistId,Name) VALUES(29,'Chic');
INSERT INTO Artists(ArtistId,Name) VALUES(30,'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO Artists(ArtistId,Name) VALUES(31,'Chico Buarque');
INSERT INTO Artists(ArtistId,Name) VALUES(32,'Chico Science & Nacao Zumbi');
INSERT INTO Artists(ArtistId,Name) VALUES(33,'Chris Cornell');
INSERT INTO Artists(ArtistId,Name) VALUES(34,'Christopher O Riley');
INSERT INTO Artists(ArtistId,Name) VALUES(35,'Cidade Negra');
INSERT INTO Artists(ArtistId,Name) VALUES(36,'Claudio Zoli');
INSERT INTO Artists(ArtistId,Name) VALUES(37,'Creedence Clearwater Revival');
INSERT INTO Artists(ArtistId,Name) VALUES(38,'David Coverdale');
INSERT INTO Artists(ArtistId,Name) VALUES(39,'Deep Purple');
INSERT INTO Artists(ArtistId,Name) VALUES(40,'Dennis Chambers');
INSERT INTO Artists(ArtistId,Name) VALUES(41,'Djavan');
INSERT INTO Artists(ArtistId,Name) VALUES(42,'Donna Summer');
INSERT INTO Artists(ArtistId,Name) VALUES(43,'Dread Zeppelin');
INSERT INTO Artists(ArtistId,Name) VALUES(44,'Ed Motta');
INSERT INTO Artists(ArtistId,Name) VALUES(45,'Edo de Waart & San Francisco Symphony');
INSERT INTO Artists(ArtistId,Name) VALUES(46,'Elis Regina');
INSERT INTO Artists(ArtistId,Name) VALUES(47,'English Concert & Trevor Pinnock');
INSERT INTO Artists(ArtistId,Name) VALUES(48,'Eric Clapton');
INSERT INTO Artists(ArtistId,Name) VALUES(49,'Eugene Ormandy');
INSERT INTO Artists(ArtistId,Name) VALUES(50,'Faith No More');
INSERT INTO Artists(ArtistId,Name) VALUES(51,'Falamansa');
INSERT INTO Artists(ArtistId,Name) VALUES(52,'Foo Fighters');
INSERT INTO Artists(ArtistId,Name) VALUES(53,'Frank Zappa & Captain Beefheart');
INSERT INTO Artists(ArtistId,Name) VALUES(54,'Funk Como Le Gusta');
INSERT INTO Artists(ArtistId,Name) VALUES(55,'Gilberto Gil');
INSERT INTO Artists(ArtistId,Name) VALUES(56,'Godsmack');
INSERT INTO Artists(ArtistId,Name) VALUES(57,'Gonzaguinha');
INSERT INTO Artists(ArtistId,Name) VALUES(58,'Goteborgs Symfoniker & Neeme Jarvi');
INSERT INTO Artists(ArtistId,Name) VALUES(59,'Guns N Roses');
INSERT INTO Artists(ArtistId,Name) VALUES(60,'Incognito');
INSERT INTO Artists(ArtistId,Name) VALUES(61,'Iron Maiden');
INSERT INTO Artists(ArtistId,Name) VALUES(62,'James Levine');
INSERT INTO Artists(ArtistId,Name) VALUES(63,'Jamiroquai');
INSERT INTO Artists(ArtistId,Name) VALUES(64,'Jimi Hendrix');
INSERT INTO Artists(ArtistId,Name) VALUES(65,'Joe Satriani');
INSERT INTO Artists(ArtistId,Name) VALUES(66,'Jorge Ben');
INSERT INTO Artists(ArtistId,Name) VALUES(67,'Jota Quest');
INSERT INTO Artists(ArtistId,Name) VALUES(68,'Judas Priest');
INSERT INTO Artists(ArtistId,Name) VALUES(69,'Kent Nagano and Orchestre de l Opera de Lyon');
INSERT INTO Artists(ArtistId,Name) VALUES(70,'Kiss');
INSERT INTO Artists(ArtistId,Name) VALUES(71,'Led Zeppelin');
INSERT INTO Artists(ArtistId,Name) VALUES(72,'Legiao Urbana');
INSERT INTO Artists(ArtistId,Name) VALUES(73,'Lenny Kravitz');
INSERT INTO Artists(ArtistId,Name) VALUES(74,'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO Artists(ArtistId,Name) VALUES(75,'Luciana Souza/Romero Lubambo');
INSERT INTO Artists(ArtistId,Name) VALUES(76,'Marcos Valle');
INSERT INTO Artists(ArtistId,Name) VALUES(77,'Marillion');
INSERT INTO Artists(ArtistId,Name) VALUES(78,'Marisa Monte');
INSERT INTO Artists(ArtistId,Name) VALUES(79,'Martin Roscoe');
INSERT INTO Artists(ArtistId,Name) VALUES(80,'Metallica');
INSERT INTO Artists(ArtistId,Name) VALUES(81,'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO Artists(ArtistId,Name) VALUES(82,'Miles Davis');
INSERT INTO Artists(ArtistId,Name) VALUES(83,'Milton Nascimento');
INSERT INTO Artists(ArtistId,Name) VALUES(84,'Motley Crue');
INSERT INTO Artists(ArtistId,Name) VALUES(85,'Motorhead');
INSERT INTO Artists(ArtistId,Name) VALUES(86,'Nash Ensemble');
INSERT INTO Artists(ArtistId,Name) VALUES(87,'Nicolaus Esterhazy Sinfonia');
INSERT INTO Artists(ArtistId,Name) VALUES(88,'Nirvana');
INSERT INTO Artists(ArtistId,Name) VALUES(89,'O Terco');
INSERT INTO Artists(ArtistId,Name) VALUES(90,'Olodum');
INSERT INTO Artists(ArtistId,Name) VALUES(91,'Orchestra of The Age of Enlightenment');
INSERT INTO Artists(ArtistId,Name) VALUES(92,'Os Paralamas Do Sucesso');
INSERT INTO Artists(ArtistId,Name) VALUES(93,'Ozzy Osbourne');
INSERT INTO Artists(ArtistId,Name) VALUES(94,'Page & Plant');
INSERT INTO Artists(ArtistId,Name) VALUES(95,'Paul D Ianno');
INSERT INTO Artists(ArtistId,Name) VALUES(96,'Pearl Jam');
INSERT INTO Artists(ArtistId,Name) VALUES(97,'Pink Floyd');
INSERT INTO Artists(ArtistId,Name) VALUES(98,'Queen');
INSERT INTO Artists(ArtistId,Name) VALUES(99,'R.E.M.');
INSERT INTO Artists(ArtistId,Name) VALUES(100,'Raul Seixas');
INSERT INTO Artists(ArtistId,Name) VALUES(101,'Red Hot Chili Peppers');
INSERT INTO Artists(ArtistId,Name) VALUES(102,'Roger Norrington, London Classical Players');
INSERT INTO Artists(ArtistId,Name) VALUES(103,'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO Artists(ArtistId,Name) VALUES(104,'Rush');
INSERT INTO Artists(ArtistId,Name) VALUES(105,'Santana');
INSERT INTO Artists(ArtistId,Name) VALUES(106,'Scholars Baroque Ensemble');
INSERT INTO Artists(ArtistId,Name) VALUES(107,'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO Artists(ArtistId,Name) VALUES(108,'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO Artists(ArtistId,Name) VALUES(109,'Skank');
INSERT INTO Artists(ArtistId,Name) VALUES(110,'Soundgarden');
INSERT INTO Artists(ArtistId,Name) VALUES(111,'Spyro Gyra');
INSERT INTO Artists(ArtistId,Name) VALUES(112,'Stevie Ray Vaughan & Double Trouble');
INSERT INTO Artists(ArtistId,Name) VALUES(113,'Stone Temple Pilots');
INSERT INTO Artists(ArtistId,Name) VALUES(114,'System Of A Down');
INSERT INTO Artists(ArtistId,Name) VALUES(115,'Temple of the Dog');
INSERT INTO Artists(ArtistId,Name) VALUES(116,'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO Artists(ArtistId,Name) VALUES(117,'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO Artists(ArtistId,Name) VALUES(118,'The Black Crowes');
INSERT INTO Artists(ArtistId,Name) VALUES(119,'The Cult');
INSERT INTO Artists(ArtistId,Name) VALUES(120,'The Doors');
INSERT INTO Artists(ArtistId,Name) VALUES(121,'The King s Singers');
INSERT INTO Artists(ArtistId,Name) VALUES(122,'The Police');
INSERT INTO Artists(ArtistId,Name) VALUES(123,'The Posies');
INSERT INTO Artists(ArtistId,Name) VALUES(124,'The Rolling Stones');
INSERT INTO Artists(ArtistId,Name) VALUES(125,'The Who');
INSERT INTO Artists(ArtistId,Name) VALUES(126,'Tim Maia');
INSERT INTO Artists(ArtistId,Name) VALUES(127,'Ton Koopman');
INSERT INTO Artists(ArtistId,Name) VALUES(128,'U2');
INSERT INTO Artists(ArtistId,Name) VALUES(129,'UB40');
INSERT INTO Artists(ArtistId,Name) VALUES(130,'Van Halen');
INSERT INTO Artists(ArtistId,Name) VALUES(131,'Various Artists');
INSERT INTO Artists(ArtistId,Name) VALUES(132,'Velvet Revolver');
INSERT INTO Artists(ArtistId,Name) VALUES(133,'Vinicius De Moraes');
INSERT INTO Artists(ArtistId,Name) VALUES(134,'Wilhelm Kempff');
INSERT INTO Artists(ArtistId,Name) VALUES(135,'Yehudi Menuhin');
INSERT INTO Artists(ArtistId,Name) VALUES(136,'Yo-Yo Ma');
INSERT INTO Artists(ArtistId,Name) VALUES(137,'Zeca Pagodinho');
